firm:
  public:
    controller:     'public'
    views:          'trst'
    layout:         'layout'
    page:
      title:        'Trading Company Ltd.'
      header:       'Trading motto'
      footer_text:  '&copy; 2005-2014 Trading Company Ltd.'
      footer_title: 'Ferenc-Loránt Kiss'
  system:
    page:
      title:        'TrustSys - Trading'
      header:       'TrustSys Trade'
      footer_text:  '&copy; 2005-2014 kfl62'
      footer_title: 'Ferenc-Loránt Kiss'

  sass_dir:     'system/assets/stylesheets'
  css_dir:      'public/stylesheets'
  css_path:     '/stylesheets'
  css_file:     'trds.css'
  images_dir:   'public/images/trds'
  images_path:  '/images/trds'
  i18n_path:    'trds'
  js_path:      'trds'

  models_path:  [trst, trds]
  db_devel:     'trst_trds'
  db_test:      'trst_test'
  db_prod:      'trst_trds'
